[tool.poetry]
name = "bbb"
version = "0.0.1"
description = "Wrong mark when multiple depenedncy given"
authors = []

[tool.poetry.dependencies]
python = ">=3.9"
itsdangerous = [
    {version = "2.0.1", python = "<3.10"},
    {version = "^2.0.2", python = ">=3.10"}
]